In [37]:
import  torch 
from torch.autograd import Variable
import torch.nn as nn

In [38]:
embeding_leftweight = Variable(nn.init.uniform_(torch.randn(5,4), a=0, b=0.1),requires_grad = True)

In [39]:
context_left = Variable(torch.randn(5,5),requires_grad= True)


In [45]:
 y =context_left.mm(embeding_leftweight)

In [48]:
y.backward(torch.ones(5,4))

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [49]:
context_left.grad

tensor([[0.1813, 0.2358, 0.2678, 0.2545, 0.1507],
        [0.1813, 0.2358, 0.2678, 0.2545, 0.1507],
        [0.1813, 0.2358, 0.2678, 0.2545, 0.1507],
        [0.1813, 0.2358, 0.2678, 0.2545, 0.1507],
        [0.1813, 0.2358, 0.2678, 0.2545, 0.1507]])

In [50]:
context_left

tensor([[ 0.5651, -1.1551, -0.5496,  1.6537, -0.1682],
        [ 0.2507,  0.3130, -0.6467,  1.5113, -0.3673],
        [-0.3354,  1.0079,  0.0147,  0.5377,  0.5452],
        [ 0.0966,  0.1328, -0.5117,  0.2207,  0.8816],
        [ 0.2905,  1.7970,  0.4214,  0.1812,  0.0208]], requires_grad=True)

In [52]:
embeding_leftweight.grad

tensor([[ 0.8675,  0.8675,  0.8675,  0.8675],
        [ 2.0957,  2.0957,  2.0957,  2.0957],
        [-1.2719, -1.2719, -1.2719, -1.2719],
        [ 4.1047,  4.1047,  4.1047,  4.1047],
        [ 0.9121,  0.9121,  0.9121,  0.9121]])

In [53]:
a = torch.randn(2,3)
b = torch.randn(2,3)
a+b

tensor([[-1.0625,  0.3005, -1.0818],
        [-0.3279, -0.0631,  0.3954]])

In [54]:
torch.tanh(a)

tensor([[ 0.2060, -0.0485,  0.1944],
        [ 0.6018,  0.2845, -0.7076]])

In [56]:
f = torch.sigmoid
f(a)

tensor([[0.5521, 0.4879, 0.5491],
        [0.6673, 0.5726, 0.2927]])

In [57]:
a

tensor([[ 0.2090, -0.0486,  0.1969],
        [ 0.6960,  0.2926, -0.8824]])

In [62]:
a[0][-1:]

tensor([0.1969])

In [64]:
import numpy as np

b = np.random.randn(3)

In [66]:
b

array([-0.19346252,  0.01576914, -1.79707478])

In [78]:
c= [2,3,4,5]
d =c.reverse()

In [80]:
c

[5, 4, 3, 2]

In [82]:
b

array([-0.19346252,  0.01576914, -1.79707478])

In [83]:
a

tensor([[ 0.2090, -0.0486,  0.1969],
        [ 0.6960,  0.2926, -0.8824]])

In [119]:
a = torch.randn(12,5,10)
b= torch.split(a,split_size_or_sections=1, dim =1)

In [121]:
c= [word.squeeze(dim =1) for word in b]

In [122]:
d =torch.stack(c,dim=1)

In [123]:
d.size()

torch.Size([12, 5, 10])

In [124]:
d== a

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        

In [118]:
b[0].size()

torch.Size([12, 1, 10])

In [111]:
a.size()

torch.Size([12, 5, 10])